# Change these first
owner: rediacc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # Production Services
  - name: Rediacc Main Site
    url: https://www.rediacc.com
    icon: https://www.rediacc.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
    maxResponseTime: 5000
    
  - name: Rediacc Sandbox
    url: https://sandbox.rediacc.com
    icon: https://www.rediacc.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
    maxResponseTime: 5000
    
  # Infrastructure Services
  - name: Docker Registry
    url: https://registry.rediacc.com/v2/
    icon: https://www.docker.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 3000
    
  - name: License Service
    url: https://lic.rediacc.com
    icon: https://www.rediacc.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 404
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rediacc.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.rediacc.com/img/logo_black.png
  name: Rediacc Infrastructure Status
  faviconUrl: https://www.rediacc.com/favicon.ico
  introTitle: "**Rediacc Infrastructure Status**"
  introMessage: Real-time monitoring and status updates for all Rediacc services and infrastructure components.
  navbar:
    - title: Status
      href: /
    - title: Rediacc
      href: https://www.rediacc.com
    - title: Documentation
      href: https://www.rediacc.com/docs

# Configuration
assignees:
  - rediacc

# Status website theme - using light for clean, professional look
theme: light

# Show incident history for last 30 days
incidentHistoryDays: 30

# Custom CSS for Rediacc branding
customBodyHtml: |
  <style>
    :root {
      --color-primary: #000000;
      --color-secondary: #ffffff;
      --color-accent: #333333;
      --color-success: #10b981;
      --color-error: #ef4444;
      --color-warning: #f59e0b;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    }
    
    .logo img {
      max-height: 48px;
      width: auto;
    }
    
    header {
      background: #ffffff;
      border-bottom: 1px solid #e5e7eb;
    }
    
    .navigation__link {
      color: #000000;
      font-weight: 500;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-size: 14px;
    }
    
    .navigation__link:hover {
      color: #666666;
    }
    
    .live-status {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
    }
    
    .site-status {
      border-radius: 8px;
      transition: all 0.3s ease;
    }
    
    .site-status:hover {
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
      transform: translateY(-2px);
    }
    
    h1, h2, h3 {
      color: #000000;
      font-weight: 600;
    }
    
    .footer {
      background: #000000;
      color: #ffffff;
    }
    
    .footer a {
      color: #ffffff;
      opacity: 0.8;
    }
    
    .footer a:hover {
      opacity: 1;
    }
    
    /* Professional status indicators */
    .status-up {
      background: #10b981;
    }
    
    .status-degraded {
      background: #f59e0b;
    }
    
    .status-down {
      background: #ef4444;
    }
    
    /* Clean button styling */
    button, .button {
      background: #000000;
      color: #ffffff;
      border: none;
      padding: 10px 20px;
      border-radius: 4px;
      font-weight: 500;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-size: 14px;
      transition: background 0.3s ease;
    }
    
    button:hover, .button:hover {
      background: #333333;
    }
  </style>

# Email notifications configuration
notifications:
  - type: email

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
