# Change these first
owner: rediacc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # Production Services
  - name: Rediacc Main Site
    url: https://www.rediacc.com
    icon: https://www.rediacc.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
    maxResponseTime: 5000
    
  - name: Rediacc Sandbox
    url: https://sandbox.rediacc.com
    icon: https://www.rediacc.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
    maxResponseTime: 5000
    
  # Infrastructure Services
  - name: Docker Registry
    url: https://registry.rediacc.com/v2/
    icon: https://www.docker.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 3000
    
  - name: License Service
    url: https://lic.rediacc.com
    icon: https://www.rediacc.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 404
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rediacc.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rediacc Status
  introTitle: "**Rediacc Status Page**"
  introMessage: This status page monitors the uptime and performance of Rediacc services. Powered by **[Upptime](https://upptime.js.org)** and GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Rediacc
      href: https://www.rediacc.com

# Configuration
assignees:
  - rediacc

# Status website theme
theme: ocean

# Show incident history for last 30 days
incidentHistoryDays: 30

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
