# Change these first
owner: rediacc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Rediacc
    url: https://www.rediacc.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rediacc.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rediacc Status
  introTitle: "**Rediacc Status Page**"
  introMessage: This status page monitors the uptime and performance of Rediacc services. Powered by **[Upptime](https://upptime.js.org)** and GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
